table View_Shipment_SKU_Delivery
	lineageTag: 58984668-9e1b-4409-93d0-2dd42faacd4a

	column RecordStatus
		dataType: string
		lineageTag: 9f9a14ad-1557-4bc9-a454-25cd76c41ce2
		summarizeBy: none
		sourceColumn: RecordStatus

		annotation SummarizationSetBy = Automatic

	column CreatedOnDate
		dataType: dateTime
		formatString: General Date
		lineageTag: fa30c64d-5cac-405a-9faf-4dd7f5263b18
		summarizeBy: none
		sourceColumn: CreatedOnDate

		variation Variation
			isDefault
			relationship: d172d95b-f816-4f88-848a-e28071918462
			defaultHierarchy: LocalDateTable_e9c3db99-3be8-474d-a5b4-c6f7d55108dd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column UpdatedOnDate
		dataType: dateTime
		formatString: General Date
		lineageTag: b2ee2de0-5b9d-4665-8905-30c7f90dd13e
		summarizeBy: none
		sourceColumn: UpdatedOnDate

		variation Variation
			isDefault
			relationship: 0bd8a054-d956-4471-8b63-df09d5a4d905
			defaultHierarchy: LocalDateTable_eef34273-dde3-4949-a7cc-74fb4c55ec20.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CPOSKUDeliveryID
		dataType: string
		lineageTag: fcc17ef8-42ef-4524-9e37-10bc688cb362
		summarizeBy: none
		sourceColumn: CPOSKUDeliveryID

		annotation SummarizationSetBy = Automatic

	column CPOSKUQuantity
		dataType: int64
		formatString: 0
		lineageTag: de993854-de7e-4ddc-91dd-761a33f61cf6
		summarizeBy: sum
		sourceColumn: CPOSKUQuantity

		annotation SummarizationSetBy = Automatic

	column FPOSKUQuantity
		dataType: int64
		formatString: 0
		lineageTag: 5b08635c-3cb0-40f4-b458-bb8217a71c20
		summarizeBy: sum
		sourceColumn: FPOSKUQuantity

		annotation SummarizationSetBy = Automatic

	column CPOSKUID
		dataType: string
		lineageTag: c2e862a1-badd-49f4-a249-67f94885f378
		summarizeBy: none
		sourceColumn: CPOSKUID

		annotation SummarizationSetBy = Automatic

	column CreatedByUserID
		dataType: string
		lineageTag: d56c9c6c-ca75-4476-bc21-e644781d500f
		summarizeBy: none
		sourceColumn: CreatedByUserID

		annotation SummarizationSetBy = Automatic

	column UpdatedByUserID
		dataType: string
		lineageTag: 1f830f41-90bb-4ca3-ba21-82d4f325df68
		summarizeBy: none
		sourceColumn: UpdatedByUserID

		annotation SummarizationSetBy = Automatic

	column CPOStyleDeliveryID
		dataType: string
		lineageTag: 0f18a6fb-9d91-479f-8257-7ce2001caddc
		summarizeBy: none
		sourceColumn: CPOStyleDeliveryID

		annotation SummarizationSetBy = Automatic

	column SKUShipQuantity
		dataType: int64
		formatString: 0
		lineageTag: d90baa6e-fe0f-4199-9721-2e97319919b2
		summarizeBy: sum
		sourceColumn: SKUShipQuantity

		annotation SummarizationSetBy = Automatic

	column FPOSKUVendorPrice
		dataType: double
		lineageTag: e06b921d-71df-4668-9648-d97f05e9de57
		summarizeBy: sum
		sourceColumn: FPOSKUVendorPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CPOSKUCustomerPrice
		dataType: double
		lineageTag: a1ea4326-1fe6-4426-95a5-ff47a0c33ccc
		summarizeBy: sum
		sourceColumn: CPOSKUCustomerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column margin
		dataType: double
		lineageTag: a7ed3e8e-46bc-42a0-854c-3d2d3910d3f7
		summarizeBy: sum
		sourceColumn: margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShippedValue = View_Shipment_SKU_Delivery[SKUShipQuantity] * View_Shipment_SKU_Delivery[CPOSKUCustomerPrice]
		lineageTag: 7a93c661-4bc4-4aef-ac3f-1d650a2269db
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShippedMargin = View_Shipment_SKU_Delivery[SKUShipQuantity] * View_Shipment_SKU_Delivery[margin]
		lineageTag: 4594a7a3-9da7-4cc6-a205-641d66b9efce
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition View_Shipment_SKU_Delivery = m
		mode: import
		source =
				let
				    Source = Sql.Databases("52.220.68.78"),
				    zinfotrek = Source{[Name="zinfotrek"]}[Data],
				    dbo_View_Shipment_SKU_Delivery = zinfotrek{[Schema="dbo",Item="View_Shipment_SKU_Delivery"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_View_Shipment_SKU_Delivery, each [SKUShipQuantity] > 0)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

