// Write your formula below, select 'Run' to try it out. When ready, select 'Update model' to add the measure to your model.
DEFINE
	MEASURE 'zCPO_STYLE_DELIVERY_F'[New Measure] = COUNTROWS('zCPO_STYLE_DELIVERY_F')

EVALUATE
	SUMMARIZECOLUMNS(
		"New Measure", [New Measure]
	)